services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=location_service_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=location'
    ports:
      - '5433:5432'
