spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/location_service_db
    username: location
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true