CREATE TABLE locations
(
    id               BIGINT           NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_member_id BIGINT           NOT NULL,
    user_id          BIGINT           NOT NULL,
    latitude         DOUBLE PRECISION NOT NULL,
    longitude        DOUBLE PRECISION NOT NULL,
    created_at       TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_locations_users_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_locations_family_members_family_member_id FOREIGN KEY (family_member_id) REFERENCES family_members(id)

)