CREATE TABLE families
(
    id         BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    user_id    BIGINT      NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT fk_families_users_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_families_name_user_id UNIQUE (name, user_id)
)