CREATE TABLE family_members
(
    id            BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL,
    family_id     BIGINT    NOT NULL,
    request_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '7 DAYS',
    approved      BOOLEAN   NOT NULL DEFAULT FALSE,
    approved_date TIMESTAMP NULL,
    CONSTRAINT fk_family_members_users_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_family_members_families_family_id FOREIGN KEY (family_id) REFERENCES families (id)
)