CREATE TABLE users
(
    id         BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50) NOT NULL UNIQUE,
    password   VARCHAR(50) NOT NULL,
    email      VARCHAR(50) NOT NULL UNIQUE,
    name       VARCHAR(50) NOT NULL,
    surname    VARCHAR(50) NOT NULL,
    birthdate  DATE        NULL,
    gender     CHAR(1)     NULL,
    address    VARCHAR(50) NULL,
    role_id    INT         NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_users_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id)
)